Work1/Models/Blood.cs
using System;
using System.Collections.Generic;

namespace Work.Models
{
    public partial class Blood
    {
        public int Id { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? ExamDate { get; set; }
        public DateTime? ResultsDate { get; set; }
        public string Description { get; set; }
        public decimal? Hemoglobin { get; set; }
        public decimal? Hematocrit { get; set; }
        public decimal? WhiteBloodCellCount { get; set; }
        public decimal? RedBloodCellCount { get; set; }
    }
}

Work1/Models/ErrorViewModel.cs
using System;

namespace Work.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Work1/Models/WorkContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Work.Models
{
    public partial class WorkContext : DbContext
    {
        public WorkContext()
        {
        }

        public WorkContext(DbContextOptions<WorkContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Blood> Blood { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Server=DESKTOP-4U2QEMU\\SQLEXPRESS;Database=Work;Trusted_Connection=True;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blood>(entity =>
            {
                entity.Property(e => e.DateCreated)
                    .HasColumnName("Date Created")
                    .HasColumnType("datetime");

                entity.Property(e => e.Description)
                    .HasColumnName("Description ")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ExamDate)
                    .HasColumnName(" Exam Date ")
                    .HasColumnType("datetime");

                entity.Property(e => e.Hematocrit)
                    .HasColumnName("Hematocrit ")
                    .HasColumnType("decimal(10, 2)");

                entity.Property(e => e.Hemoglobin).HasColumnType("decimal(10, 2)");

                entity.Property(e => e.RedBloodCellCount)
                    .HasColumnName("Red Blood Cell Count")
                    .HasColumnType("decimal(10, 2)");

                entity.Property(e => e.ResultsDate)
                    .HasColumnName(" Results Date ")
                    .HasColumnType("datetime");

                entity.Property(e => e.WhiteBloodCellCount)
                    .HasColumnName("White Blood Cell Count")
                    .HasColumnType("decimal(10, 2)");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

Work1/Controllers/BloodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Work.Models;

namespace Work.Controllers
{
    public class BloodController : Controller
    {
        private readonly WorkContext _context;

        public BloodController(WorkContext context)
        {
            _context = context;
        }

        // GET: Blood
        public async Task<IActionResult> Index()
        {
            return View(await _context.Blood.ToListAsync());
        }

        // GET: Blood/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blood = await _context.Blood
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blood == null)
            {
                return NotFound();
            }

            return View(blood);
        }

        // GET: Blood/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Blood/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DateCreated,ExamDate,ResultsDate,Description,Hemoglobin,Hematocrit,WhiteBloodCellCount,RedBloodCellCount")] Blood blood)
        {
            if (ModelState.IsValid)
            {
                _context.Add(blood);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(blood);
        }

        // GET: Blood/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blood = await _context.Blood.FindAsync(id);
            if (blood == null)
            {
                return NotFound();
            }
            return View(blood);
        }

        // POST: Blood/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DateCreated,ExamDate,ResultsDate,Description,Hemoglobin,Hematocrit,WhiteBloodCellCount,RedBloodCellCount")] Blood blood)
        {
            if (id != blood.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blood);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BloodExists(blood.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(blood);
        }

        // GET: Blood/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blood = await _context.Blood
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blood == null)
            {
                return NotFound();
            }

            return View(blood);
        }

        // POST: Blood/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blood = await _context.Blood.FindAsync(id);
            _context.Blood.Remove(blood);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BloodExists(int id)
        {
            return _context.Blood.Any(e => e.Id == id);
        }
    }
}

Work1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Work.Models;

namespace Work.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Work1/Views/Blood/Create.cshtml
@model Work.Models.Blood

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Blood</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExamDate" class="control-label"></label>
                <input asp-for="ExamDate" class="form-control" />
                <span asp-validation-for="ExamDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResultsDate" class="control-label"></label>
                <input asp-for="ResultsDate" class="form-control" />
                <span asp-validation-for="ResultsDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hemoglobin" class="control-label"></label>
                <input asp-for="Hemoglobin" class="form-control" />
                <span asp-validation-for="Hemoglobin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hematocrit" class="control-label"></label>
                <input asp-for="Hematocrit" class="form-control" />
                <span asp-validation-for="Hematocrit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WhiteBloodCellCount" class="control-label"></label>
                <input asp-for="WhiteBloodCellCount" class="form-control" />
                <span asp-validation-for="WhiteBloodCellCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RedBloodCellCount" class="control-label"></label>
                <input asp-for="RedBloodCellCount" class="form-control" />
                <span asp-validation-for="RedBloodCellCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Work1/Views/Blood/Delete.cshtml
@model Work.Models.Blood

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Blood</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExamDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExamDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ResultsDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ResultsDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hemoglobin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hemoglobin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hematocrit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hematocrit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WhiteBloodCellCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WhiteBloodCellCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RedBloodCellCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RedBloodCellCount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Work1/Views/Blood/Details.cshtml
@model Work.Models.Blood

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Blood</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExamDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExamDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ResultsDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ResultsDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hemoglobin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hemoglobin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hematocrit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hematocrit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WhiteBloodCellCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WhiteBloodCellCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RedBloodCellCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RedBloodCellCount)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Work1/Views/Blood/Edit.cshtml
@model Work.Models.Blood

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Blood</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExamDate" class="control-label"></label>
                <input asp-for="ExamDate" class="form-control" />
                <span asp-validation-for="ExamDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResultsDate" class="control-label"></label>
                <input asp-for="ResultsDate" class="form-control" />
                <span asp-validation-for="ResultsDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hemoglobin" class="control-label"></label>
                <input asp-for="Hemoglobin" class="form-control" />
                <span asp-validation-for="Hemoglobin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hematocrit" class="control-label"></label>
                <input asp-for="Hematocrit" class="form-control" />
                <span asp-validation-for="Hematocrit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WhiteBloodCellCount" class="control-label"></label>
                <input asp-for="WhiteBloodCellCount" class="form-control" />
                <span asp-validation-for="WhiteBloodCellCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RedBloodCellCount" class="control-label"></label>
                <input asp-for="RedBloodCellCount" class="form-control" />
                <span asp-validation-for="RedBloodCellCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Work1/Views/Blood/Index.cshtml
@model IEnumerable<Work.Models.Blood>

@{
    ViewData["Title"] = "Index";
    var Dates = new List<DateTime?>();
    var hemoglobin = new List<decimal?>();
    var hematocrit = new List<decimal?>();
    var redblood  = new List<decimal?>();
    var whiteblood = new List<decimal?>();
    foreach (var item in Model)
    {
        Dates.Add(item.ResultsDate);
        hemoglobin.Add(item.Hemoglobin);
        hematocrit.Add(item.Hematocrit);
        redblood.Add(item.RedBloodCellCount);
        whiteblood.Add(item.WhiteBloodCellCount);

    }

}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExamDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ResultsDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hemoglobin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hematocrit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WhiteBloodCellCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RedBloodCellCount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExamDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ResultsDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hemoglobin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hematocrit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WhiteBloodCellCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RedBloodCellCount)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<figure class="highcharts-figure">
    <div id="container"></div>
    <p class="highcharts-description">
        This chart shows how data labels can be added to the data series. This
        can increase readability and comprehension for small datasets.
    </p>
</figure>
<script>
    Highcharts.chart('container', {
        chart: {
            type: 'line'
        },
        title: {
            text: ' blood Work report'
        },

        xAxis: {
            categories:       @Html.Raw(Json.Serialize(Dates))

        },
        yAxis: {
            title: {
                text: 'Values'
            }
        },

        series: [{
            name: 'Hemoglobin',
            data:@Html.Raw(Json.Serialize(hemoglobin))
        },
            {

                name: 'Hematocrit',
               data:@Html.Raw(Json.Serialize(hematocrit))

        },  {
                   name: 'RedBlood',
               data:@Html.Raw(Json.Serialize(redblood))

        },  {
                  name: 'WhiteBlood',
               data:@Html.Raw(Json.Serialize(whiteblood))

            }]
    });
</script>

Work1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Work1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Work</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                @*<div><img src="~/medchart.png" width="30" heigth="100" class="d-inline-block align-middle" /></div>*@
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Medical</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blood" asp-action="Index">BloodWork Results</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Work - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>